/*
Action types
*/
export const API_REQUEST_PUPPIES = 'API_REQUEST_PUPPIES'

export const API_SUCCESS_PUPPIES = 'API_SUCCESS_PUPPIES'

export const API_FAIL_PUPPIES = 'API_FAIL_PUPPIES'

export const API_REQUEST_KITTIES = 'API_REQUEST_KITTIES'

export const API_SUCCESS_KITTIES = 'API_SUCCESS_KITTIES'

export const API_FAIL_KITTIES = 'API_FAIL_KITTIES'

export const MINI_PREVIEW = 'MINI_PREVIEW'

export const PREV_PAGE = 'PREV_PAGE'

export const NEXT_PAGE = 'NEXT_PAGE'

export const GO_TO_PAGE = 'GO_TO_PAGE'

export const SWITCH_TAB = 'SWITCH_TAB'
